apiVersion: container.gcp.crossplane.io/v1beta2
kind: GKECluster
metadata:
  name: gke-crossplane-cluster
spec:
  forProvider:
    location: europe-central2-a
    initialClusterVersion: latest

---

apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: gke-crossplane-np
spec:
  forProvider:
    locations:
    - europe-central2-a
    clusterRef:
      name: gke-crossplane-cluster
    initialNodeCount: 1
    config:
      preemptible: true
      machineType: e2-medium
      oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    autoscaling:
      enabled: true
      minNodeCount: 1
      maxNodeCount: 2
    management:
      autoUpgrade: false
